Models/Media.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bau302TodoList.Models
{
    public class Media:BaseEntity
    {
        [StringLength(200), Required(ErrorMessage = "Bu alan doldurulmalıdır!"), DisplayName("Ad")]
        public string Name { get; set; }

        [DisplayName("Açıklama")]
        public string Description { get; set; }

        [DisplayName("Uzantı")]
        public string Extension { get; set; }

        [DisplayName("Dosya Yolu")]
        [StringLength(200)]
        public string FilePath { get; set; }

        [DisplayName("Dosya Boyutu")]
        public float FileSize { get; set; }

        [DisplayName("Yıl")]
        public int Year { get; set; }

        [DisplayName("Ay")]
        public int Month { get; set; }

        [DisplayName("İçerik Tipi")]
        [StringLength(200)]
        public string ContentType { get; set; }







    }
}

Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bau302TodoList.Models;
using System.IO;

namespace Bau302TodoList.Controllers
{
    [Authorize]

    public class MediaController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Media
        public async Task<ActionResult> Index()
        {
            return View(await db.Medias.ToListAsync());
        }

        // GET: Media/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Media media = await db.Medias.FindAsync(id);
            if (media == null)
            {
                return HttpNotFound();
            }
            return View(media);
        }

        // GET: Media/Create
        public ActionResult Create()
        {
            var media = new Media();
            return View(media);
        }

        // POST: Media/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,Extension,FilePath,FileSize,Year,Month,ContentType,CreateDate,CreatedBy,UpdateDate,UpdatedBy")] Media media)
        {
            if (ModelState.IsValid)
            {
                media.CreateDate = DateTime.Now;
                media.CreatedBy = User.Identity.Name;
                media.UpdateDate = DateTime.Now;
                media.UpdatedBy = User.Identity.Name;
                
                // upload işlemi
                if(!String.IsNullOrEmpty(media.FilePath))
                {
                    FileInfo fileinfo = new FileInfo(Server.MapPath("~" + media.FilePath));
                    media.FileSize=((float)fileinfo.Length)/((float)1024);
                    media.Extension = fileinfo.Extension;
                    media.ContentType = fileinfo.Extension;
                }

                db.Medias.Add(media);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(media);
        }

        // GET: Media/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Media media = await db.Medias.FindAsync(id);
            if (media == null)
            {
                return HttpNotFound();
            }
            return View(media);
        }

        // POST: Media/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,Extension,FilePath,FileSize,Year,Month,ContentType,CreateDate,CreatedBy,UpdateDate,UpdatedBy")] Media media)
        {
            if (ModelState.IsValid)
            {
                media.UpdateDate = DateTime.Now;
                media.UpdatedBy = User.Identity.Name;

                // upload işlemi

                if (!String.IsNullOrEmpty(media.FilePath))
                {
                    FileInfo fileinfo = new FileInfo(Server.MapPath("~" + media.FilePath));
                    media.FileSize = ((float)fileinfo.Length) / ((float)1024);
                    media.Extension = fileinfo.Extension;
                    media.ContentType = fileinfo.Extension;
                }
                db.Entry(media).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(media);
        }

        // GET: Media/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Media media = await db.Medias.FindAsync(id);
            if (media == null)
            {
                return HttpNotFound();
            }
            return View(media);
        }

        // POST: Media/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Media media = await db.Medias.FindAsync(id);
            db.Medias.Remove(media);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult SaveUploadedFile()
        {

            bool isSavedSuccessfully = true;
            string fName = "";
            string categoryFolder = "";

            try
            {
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fileName];
                    if (file != null && file.ContentLength > 0)
                    {
                        var uploadLocation = Server.MapPath("~/uploads");
                        categoryFolder = "/" + DateTime.Now.Year + "-" + DateTime.Now.Month + "/";
                        fName = file.FileName;
                        var extension = Path.GetExtension(fName).ToLower();
                        var contentType = file.ContentType;
                        float fileSize = ((float)file.ContentLength) / ((float)1024);
                        if (!Directory.Exists(uploadLocation + categoryFolder))
                        {
                            Directory.CreateDirectory(uploadLocation + categoryFolder);
                        }
                        if (!System.IO.File.Exists(uploadLocation + categoryFolder + fName))
                        {
                            file.SaveAs(uploadLocation + categoryFolder + fName);
                        }
                        else
                        {
                            throw new Exception("Dosya zaten mevcut.");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
                
            }
            if (isSavedSuccessfully)
            {
                return Json(new { Message = "/uploads" + categoryFolder + fName, success = true });
            }
            else
            {
                return Json(new { Message = "Hata oldu,Dosya kaydedilemedi.", success = false });
            }
        }
    }
}

Views/Media/Create.cshtml
@model Bau302TodoList.Models.Media

@{
    ViewBag.Title = "Yeni Oluştur";
}
<link href="~/assets/global/plugins/dropzone/dropzone.min.css" rel="stylesheet" type="text/css" />
<link href="~/assets/global/plugins/dropzone/basic.min.css" rel="stylesheet" type="text/css" />
<style>
    #my-dropzone {
        background: gray;
        border: black dashed 3px;
        width: 450px;
        padding: 50px;
        margin-left: 15px;
        text-align: center;
        color: white;
    }
</style>

<h2>Yeni Oluştur</h2>


@using (Html.BeginForm("Create", "Media", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dosya</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(m => m.Extension)

        <div class="form-group">
            <label class="control-label col-md-2">Dosya</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Dosya Yükle</label>
            <div class="col-md-10 dropzone dropzone-file-area" id="my-dropzone">
                <h3 class="sbold">Dosyayı buraya sürükleyin veya tıklayın</h3>
            </div>
        </div>

        @Html.HiddenFor(m => m.FileSize)
        @Html.HiddenFor(m => m.Year)
        @Html.HiddenFor(m => m.Month)
        @Html.HiddenFor(m => m.ContentType)
        @Html.HiddenFor(m => m.CreateDate)
        @Html.HiddenFor(m => m.CreatedBy)
        @Html.HiddenFor(m => m.UpdateDate)
        @Html.HiddenFor(m => m.UpdatedBy)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

@section Scripts {
    <script src="~/assets/global/plugins/dropzone/dropzone.min.js" type="text/javascript"></script>
    <script>
        Dropzone.autoDiscover = false;
        $("div#my-dropzone").dropzone({
            url: "/Media/SaveUploadedFile", uploadMultiple: false, maxFiles: 1, init: function () {
                this.on("complete", function (data) {
                    var res = JSON.parse(data.xhr.responseText);
                    $("#FilePath").val(res.Message);
                    if (res.success == false) {
                        $("#FilePath").css("border-color", "red");
                    }
                });
            }
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Media/Delete.cshtml
@model Bau302TodoList.Models.Media

@{
    ViewBag.Title = "Dosya Sil";
}

<h2>Dosya Sil</h2>

<h3>Silmek istediğinize emin misiniz?</h3>
<div>
    <h4>Dosya</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    }
</div>

Views/Media/Details.cshtml
@model Bau302TodoList.Models.Media

@{
    ViewBag.Title = "Dosya Detaylar";
}

<h2>Dosya Detaylar</h2>

<div>
    <h4>Dosya</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Listeye Geri Dön", "Index")
</p>

Views/Media/Edit.cshtml
@model Bau302TodoList.Models.Media

@{
    ViewBag.Title = "Dosya Düzenle";
}

<h2>Dosya Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dosya</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Extension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentType, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(m => m.CreateDate)
        @Html.HiddenFor(m => m.CreatedBy)
        @Html.HiddenFor(m => m.UpdateDate)
        @Html.HiddenFor(m => m.UpdatedBy)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Media/Index.cshtml
@model IEnumerable<Bau302TodoList.Models.Media>

@{
    ViewBag.Title = "Dosya Listesi";
}

<h2>Dosya Listesi</h2>

<p>
    @Html.ActionLink("Yeni Kayıt", "Create", null, new { @class = "btn btn red btn-outline" })
    <a class="dt-button buttons-excel buttons-html5 btn blue btn-outline" tabindex="0" aria-controls="sample_1" href="@Url.Action("ExportToExcel","Media")" style="float:right"><span>Excele Aktar</span></a>
    <a class="dt-button buttons-excel buttons-html5 btn purple btn-outline" tabindex="0" aria-controls="sample_1" href="@Url.Action("ExportToCsv","Media")" style="float:right"><span>Csv Aktar</span></a>
</p>
<table class="table table-striped table-hover" id="tblRecords">
    <thead>
        <tr>
            <th class="text-nowrap all">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Extension)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.FilePath)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.FileSize)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.ContentType)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.UpdateDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.UpdatedBy)
            </th>
            <th data-orderable="false" class="all">Eylemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Extension)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FilePath)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContentType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedBy)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detaylar", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Sil", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>